spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:h2:mem:products-db
  h2:
    console:
      enabled: true
  cloud:
    discovery:
      enabled: false #desactiver le service d'enregistrement
    config:
      enabled: false #desactiver le service de configuration cloud
server:
  port: 8082
